#!/usr/bin/env python3
"""Analyze vigil WAL recovery benchmark CSV: stats, plots, and markdown report.

Reads the raw CSV (branch,lines,interruption_pct,interruption_type,trial,recovery_ms),
runs a Welch t-test (WAL vs no-WAL) per (lines x pct x type) cell, computes mean,
std, 95% CI, Cohen's d, and emits:
  - bench/out/results.csv   (one row per cell, all stats)
  - bench/out/recovery_<type>.png  (faceted grouped bars, one panel per type)
  - bench/out/report.md     (full markdown report)

usage: analyze.py --raw bench/out/raw.csv --outdir bench/out
"""
import argparse
import os
import numpy as np
import pandas as pd
from scipy import stats
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt


def ci95(x):
    x = np.asarray(x, float)
    n = len(x)
    if n < 2:
        return (np.nan, np.nan)
    m, sd = x.mean(), x.std(ddof=1)
    h = stats.t.ppf(0.975, n - 1) * sd / np.sqrt(n)
    return (m - h, m + h)


def cohens_d(a, b):
    a, b = np.asarray(a, float), np.asarray(b, float)
    na, nb = len(a), len(b)
    if na < 2 or nb < 2:
        return np.nan
    sp = np.sqrt(((na - 1) * a.var(ddof=1) + (nb - 1) * b.var(ddof=1)) / (na + nb - 2))
    return (a.mean() - b.mean()) / sp if sp > 0 else np.nan


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--raw", required=True)
    ap.add_argument("--outdir", required=True)
    args = ap.parse_args()
    os.makedirs(args.outdir, exist_ok=True)

    df = pd.read_csv(args.raw)
    df = df.dropna(subset=["recovery_ms"])

    rows = []
    for (lines, pct, itype), g in df.groupby(["lines", "interruption_pct", "interruption_type"]):
        wal = g[g.branch == "wal"]["recovery_ms"].values
        no = g[g.branch == "nowal"]["recovery_ms"].values
        if len(wal) < 2 or len(no) < 2:
            continue
        t, p = stats.ttest_ind(wal, no, equal_var=False)  # Welch
        wlo, whi = ci95(wal)
        nlo, nhi = ci95(no)
        speedup = no.mean() / wal.mean() if wal.mean() > 0 else np.nan
        rows.append({
            "lines": lines, "pct": pct, "type": itype,
            "wal_mean": wal.mean(), "wal_std": wal.std(ddof=1),
            "wal_ci_lo": wlo, "wal_ci_hi": whi,
            "nowal_mean": no.mean(), "nowal_std": no.std(ddof=1),
            "nowal_ci_lo": nlo, "nowal_ci_hi": nhi,
            "delta_ms": no.mean() - wal.mean(), "speedup_x": speedup,
            "p_value": p, "cohens_d": cohens_d(wal, no),
            "significant": p < 0.05,
        })
    res = pd.DataFrame(rows).sort_values(["type", "lines", "pct"]).reset_index(drop=True)
    res.to_csv(os.path.join(args.outdir, "results.csv"), index=False)

    # ---- plots: one panel per interruption type, faceted, grouped bars over size ----
    plot_paths = {}
    for itype in sorted(res["type"].unique()):
        sub = res[(res["type"] == itype) & (res["pct"] == 100)].sort_values("lines")
        if sub.empty:
            continue
        fig, ax = plt.subplots(figsize=(9, 5))
        x = np.arange(len(sub))
        bw = 0.38
        ax.bar(x - bw / 2, sub["wal_mean"], bw,
               yerr=(sub["wal_mean"] - sub["wal_ci_lo"], sub["wal_ci_hi"] - sub["wal_mean"]),
               capsize=3, label="WAL", color="#4c72b0")
        ax.bar(x + bw / 2, sub["nowal_mean"], bw,
               yerr=(sub["nowal_mean"] - sub["nowal_ci_lo"], sub["nowal_ci_hi"] - sub["nowal_mean"]),
               capsize=3, label="no-WAL (main)", color="#dd8452")
        ax.set_xticks(x)
        ax.set_xticklabels([f"{int(n):,}" for n in sub["lines"]])
        ax.set_xlabel("log size (lines, 100% ingested)")
        ax.set_ylabel("recovery time (ms)  -- lower is better")
        ax.set_title(f"Recovery time vs log size  ({'graceful --stop' if itype=='stop' else 'crash kill -9'})")
        ax.legend()
        ax.grid(axis="y", alpha=0.3)
        fig.tight_layout()
        path = os.path.join(args.outdir, f"recovery_{itype}.png")
        fig.savefig(path, dpi=120)
        plt.close(fig)
        plot_paths[itype] = os.path.basename(path)

    # ---- markdown report ----
    def fmt(v, n=1):
        return "—" if pd.isna(v) else f"{v:.{n}f}"

    md = []
    md.append("# WAL Recovery Performance vs. Baseline (No WAL)\n")
    md.append("Generated by `scripts/analyze.py`. Treatment = `feature/wal`, "
              "Control = `main` (no persistence). Dependent variable: recovery time "
              "(daemon start → index fully queryable), measured by polling "
              "`vigil \"| count\"` until it equals the ingested line count.\n")

    md.append("## Results table\n")
    md.append("One row per cell. `Δ` = no-WAL mean − WAL mean (positive = WAL faster). "
              "`speedup` = no-WAL / WAL. Cells with p > 0.05 are flagged **inconclusive**.\n")
    md.append("| size | pct | type | WAL ms (±95% CI) | no-WAL ms (±95% CI) | Δ ms | speedup | p | Cohen's d | verdict |")
    md.append("|---|---|---|---|---|---|---|---|---|---|")
    for _, r in res.iterrows():
        wal_s = f"{fmt(r.wal_mean)} [{fmt(r.wal_ci_lo)}, {fmt(r.wal_ci_hi)}]"
        no_s = f"{fmt(r.nowal_mean)} [{fmt(r.nowal_ci_lo)}, {fmt(r.nowal_ci_hi)}]"
        verdict = ("✅ WAL faster" if (r.significant and r.delta_ms > 0)
                   else "🟥 WAL slower" if (r.significant and r.delta_ms < 0)
                   else "⚪ inconclusive")
        md.append(f"| {int(r.lines):,} | {int(r.pct)}% | {r.type} | {wal_s} | {no_s} | "
                  f"{fmt(r.delta_ms)} | {fmt(r.speedup_x,2)}× | {fmt(r.p_value,4)} | "
                  f"{fmt(r.cohens_d,2)} | {verdict} |")
    md.append("")

    md.append("## Plots\n")
    for itype, p in plot_paths.items():
        md.append(f"**{'Graceful (--stop)' if itype=='stop' else 'Crash (kill -9)'}** — 100% ingested:\n")
        md.append(f"![recovery {itype}]({p})\n")

    md.append("## Raw data\n")
    md.append("- Raw timings: [`raw.csv`](raw.csv)")
    md.append("- Per-cell stats: [`results.csv`](results.csv)\n")

    with open(os.path.join(args.outdir, "report_body.md"), "w") as f:
        f.write("\n".join(md))

    print(res.to_string(index=False))
    print("\nwrote results.csv, report_body.md, and plots to", args.outdir)


if __name__ == "__main__":
    main()
